M48
; DRILL file {KiCad 7.0.11+1} date Mon Jun 17 11:26:23 2024
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2024-06-17T11:26:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
%
G90
G05
T1
X143390Y-95730
X143390Y-100030
X150690Y-95730
M30
