M48
; DRILL file {KiCad 9.0.7+1} date 2026-02-22T23:16:14+0000
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2026-02-22T23:16:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
%
G90
G05
T1
X143390Y-95730
X143390Y-100030
X150690Y-95730
M30
